/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author dani_
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    double a,b,sum;
    String symbol, check;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(431, 535));
        setMinimumSize(new java.awt.Dimension(431, 535));
        setPreferredSize(new java.awt.Dimension(431, 535));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("7");
        jButton1.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton1.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton1.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("8");
        jButton2.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton2.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton2.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("9");
        jButton3.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton3.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton3.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setText("÷");
        jButton4.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton4.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton4.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setText("4");
        jButton5.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton5.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton5.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jButton6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton6.setText("5");
        jButton6.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton6.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton6.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jButton7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton7.setText("6");
        jButton7.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton7.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton7.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jButton8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton8.setText("+");
        jButton8.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton8.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton8.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        jButton9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton9.setText("1");
        jButton9.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton9.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton9.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jButton10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton10.setText("2");
        jButton10.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton10.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton10.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jButton11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton11.setText("3");
        jButton11.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton11.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton11.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jButton12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton12.setText("-");
        jButton12.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton12.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton12.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jButton13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton13.setText("0");
        jButton13.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton13.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton13.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 150, -1));

        jButton14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton14.setText(".");
        jButton14.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton14.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton14.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        jButton15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton15.setText("%");
        jButton15.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton15.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton15.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jButton16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton16.setText("=");
        jButton16.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton16.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton16.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, 200));

        jButton17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton17.setText("C");
        jButton17.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton17.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton17.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButton18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton18.setText("DEL");
        jButton18.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton18.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton18.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jButton19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton19.setText("±");
        jButton19.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton19.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton19.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jButton20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton20.setText("x");
        jButton20.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton20.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton20.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jButton21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton21.setText("√");
        jButton21.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton21.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton21.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jButton22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton22.setText("x2");
        jButton22.setMaximumSize(new java.awt.Dimension(70, 70));
        jButton22.setMinimumSize(new java.awt.Dimension(70, 70));
        jButton22.setPreferredSize(new java.awt.Dimension(70, 60));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("ON/OFF");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jTextField1.setBackground(new java.awt.Color(255, 234, 255));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 400, 480));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     if(jRadioButton1.isSelected()){
                  if(a!=0){
        a=a/Double.parseDouble(jTextField1.getText());
       symbol="÷";
        jTextField1.setText(jTextField1.getText()+symbol);
       }
       else{
        a=Double.parseDouble(jTextField1.getText());
       symbol="÷";
         jTextField1.setText(jTextField1.getText()+symbol);
       }
     }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       if(jRadioButton1.isSelected()){
            jTextField1.setText("");
            a=0;
            b=0;
            sum=0;
       }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
      if(jRadioButton1.isSelected()){
           if(!jTextField1.getText().equals("")){
          String Word=jTextField1.getText();
          Word=Word.substring(0,Word.length()-1);
          jTextField1.setText(Word);
          a=0;
          b=0;
          sum=0;
       }
      }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jRadioButton1.isSelected()){
           jTextField1.setText(jTextField1.getText()+jButton1.getText());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
               if(jRadioButton1.isSelected()){
                   jTextField1.setText(jTextField1.getText()+jButton2.getText());
               }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
               if(jRadioButton1.isSelected()){
                   jTextField1.setText(jTextField1.getText()+jButton3.getText());
               }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
              if(jRadioButton1.isSelected()){
                  jTextField1.setText(jTextField1.getText()+jButton5.getText());
              }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
              if(jRadioButton1.isSelected()){
                  jTextField1.setText(jTextField1.getText()+jButton6.getText());
              }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
               if(jRadioButton1.isSelected()){
                   jTextField1.setText(jTextField1.getText()+jButton7.getText());
               }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            if(jRadioButton1.isSelected()){     
               jTextField1.setText(jTextField1.getText()+jButton9.getText());
            }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(jRadioButton1.isSelected())    {
            jTextField1.setText(jTextField1.getText()+jButton10.getText());
        }  
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(jRadioButton1.isSelected()){
            jTextField1.setText(jTextField1.getText()+jButton11.getText());

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(jRadioButton1.isSelected()){
                   jTextField1.setText(jTextField1.getText()+jButton13.getText());
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       if(jRadioButton1.isSelected()){
           if(!jTextField1.getText().contains(".")&&!jTextField1.getText().equals("")){
                  jTextField1.setText(jTextField1.getText()+jButton14.getText());
       }
       }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     if(jRadioButton1.isSelected()){
            if(a!=0){
        a=a+Double.parseDouble(jTextField1.getText());
       symbol="+";
        jTextField1.setText(jTextField1.getText()+symbol);
       }
       else{
        a=Double.parseDouble(jTextField1.getText());
       symbol="+";
      jTextField1.setText(jTextField1.getText()+symbol);
       }
     }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
   if(jRadioButton1.isSelected()){
            if(a!=0){
        a=a-Double.parseDouble(jTextField1.getText());
       symbol="-";
        jTextField1.setText(jTextField1.getText()+symbol);
       }
       else{
        a=Double.parseDouble(jTextField1.getText());
       symbol="-";
         jTextField1.setText(jTextField1.getText()+symbol);
       }
   }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
     if(jRadioButton1.isSelected()){
           if(a!=0){
        a=a*Double.parseDouble(jTextField1.getText());
        symbol="x";
        jTextField1.setText(jTextField1.getText()+symbol);
       }
       else{
        a=Double.parseDouble(jTextField1.getText());
        symbol="x";
         jTextField1.setText(jTextField1.getText()+symbol);
       }
     }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       if(jRadioButton1.isSelected()){
           double percent=Double.parseDouble(jTextField1.getText())/100;
           jTextField1.setText(String.valueOf(percent));
       }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if(jRadioButton1.isSelected()){
            String secondNumber=jTextField1.getText();
            secondNumber=secondNumber.substring(secondNumber.indexOf(symbol)+1, secondNumber.length());
                  b=Double.parseDouble(secondNumber);
        jTextField1.setText("");  
        switch (symbol) {
            case "+":
               if(sum==0){
                 sum=a+b;
                 check=String.valueOf(sum);
                    if(check.endsWith(".0")){
                         jTextField1.setText(String.valueOf(Math.round(sum)));
                    }
                    else{
                        jTextField1.setText(String.valueOf(sum));   
                    }
                }
                else{
                    sum=sum+b;   
                    check=String.valueOf(sum);
                        if(check.endsWith(".0")){
                            jTextField1.setText(String.valueOf(Math.round(sum)));
                        }
                        else{
                            jTextField1.setText(String.valueOf(sum));   
                        }  
                }
                break;
            case "-":
                if(sum==0){
                 sum=a-b;
                 check=String.valueOf(sum);
                        if(check.endsWith(".0")){
                            jTextField1.setText(String.valueOf(Math.round(sum)));
                        }
                        else{
                            jTextField1.setText(String.valueOf(sum));   
                        }  
                }
                else{
                    sum=sum-b;     
                    check=String.valueOf(sum);
                        if(check.endsWith(".0")){
                            jTextField1.setText(String.valueOf(Math.round(sum)));
                        }
                        else{
                            jTextField1.setText(String.valueOf(sum));   
                        }
                }
                break;
                
             case "x":
                if(sum==0){
                 sum=a*b;
                 check=String.valueOf(sum);
                        if(check.endsWith(".0")){
                            jTextField1.setText(String.valueOf(Math.round(sum)));
                        }
                        else{
                            jTextField1.setText(String.valueOf(sum));   
                        }
                }
                else{
                    sum=sum*b; 
                    check=String.valueOf(sum);
                        if(check.endsWith(".0")){
                            jTextField1.setText(String.valueOf(Math.round(sum)));
                        }
                        else{
                            jTextField1.setText(String.valueOf(sum));   
                        }
                }
                 
                break;
             case "÷":
                if(sum==0){
                 sum=a/b;
                 check=String.valueOf(sum);
                        if(check.endsWith(".0")){
                            jTextField1.setText(String.valueOf(Math.round(sum)));
                        }
                        else{
                            jTextField1.setText(String.valueOf(sum));   
                        }  
                }
                else{
                    sum=sum/b;                
                    check=String.valueOf(sum);
                        if(check.endsWith(".0")){
                            jTextField1.setText(String.valueOf(Math.round(sum)));
                        }
                        else{
                            jTextField1.setText(String.valueOf(sum));   
                        }   
                }
                break;
            default:
                throw new AssertionError();
        }
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
    if(jRadioButton1.isSelected()){
             if(jTextField1.getText().contains(".")){
        double reverse=Double.parseDouble(jTextField1.getText());
           reverse*=-1;
           jTextField1.setText(String.valueOf(reverse));
        }   
        else{
            long reverseLong=Long.parseLong(jTextField1.getText());
            reverseLong*=-1;
             jTextField1.setText(String.valueOf(reverseLong));
        }
    }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
          if(jRadioButton1.isSelected()){
               a=Double.parseDouble(jTextField1.getText());
        a=Math.sqrt(a);
        check=String.valueOf(a);
            if(check.endsWith(".0")){
                jTextField1.setText(String.valueOf(Math.round(a)));
            }
            else{
                jTextField1.setText(String.valueOf(a));   
            }
          }
        
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
     if(jRadioButton1.isSelected()){
             a=Double.parseDouble(jTextField1.getText());
        a=Math.pow(a, 2);
        check=String.valueOf(a);
            if(check.endsWith(".0")){
                jTextField1.setText(String.valueOf(Math.round(a)));
            }
            else{
                jTextField1.setText(String.valueOf(a));   
            } 
     }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(!jRadioButton1.isSelected()){
            jTextField1.setText("");
            a=0;
            b=0;
            sum=0;
            symbol="";
            check="";
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
